default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot-labs

development:
  <<: *default

test:
  <<: *default

stage:
  <<: *default

production:
  <<: *default

coin_elite:
  <<: *default
  database: coin_elite

spot_manager:
  <<: *default
  database: spot_manager
  